// Flat ESLint config for Next.js 16 (which has removed `next lint`).
// eslint-config-next@16 已经原生导出 Linter.Config[]，直接用即可。
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const config = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    ignores: [
      ".next/**",
      "out/**",
      "node_modules/**",
      "next-env.d.ts",
      // Auto-generated by `pnpm gen:api`; regenerated in CI, drift-detection
      // compares checksums, so lint rules don't apply.
      "lib/api/schema.ts",
    ],
  },
];

export default config;
